/// Flutter icons BreatheIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BreatheIcons
///      fonts:
///       - asset: fonts/BreatheIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BreatheIcons {
  BreatheIcons._();

  static const _kFontFam = 'BreatheIcons';
  static const _kFontPkg = null;

  static const IconData lungs = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vibrate = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
